
module.exports = {
  al: 'Albania',
  fi: 'Finland',
  fr: 'France',
  de: 'Germany',
  ie: 'Ireland',
  lv: 'Latvia',
  lt: 'Lithuania',
  nl: 'Netherlands',
  no: 'Norway',
  pl: 'Poland',
  rs: 'Serbia',
  sl: 'Slovakia',
  tr: 'Turkey',
  es: 'Spain',
  dk: 'Denmark',
  bh: 'Bosnia and Herzegovina',
  ge: 'Greece',
  ee: 'Estonia',
  pt: 'Portugal',
  it: 'Italy',
  ro: 'Romania',
  hr: 'Croatia',
  hu: 'Hungary',
  mk: 'Republic of Macedonia',
  se: 'Sweden',
  ua: 'Ukraine',
};
